services:
  openvpn-client:
    build:
      context: ./build
    container_name: openvpn-client
    network_mode: "host"
    privileged: true
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - ALLOWED_SUBNETS=192.168.10.0/24
      - CONFIG_FILE=gate_openvpn_remote_access_l3.ovpn
      - AUTH_SECRET=
    volumes:
      - ./local:/config
    restart: on-failure
